language: python
python:
  - "3.7"
install:
  - python setup.py install
script:
  - python tests.py
after_success:
  # push tag as well
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
      python setup.py sdist bdist_wheel ;
      twine upload dist/* ;
    fi
